-- ============================================================
-- DAILY LEGAL SNIPPET — Setup de la base Supabase (proyecto NUEVO, separado del Smart Snippet)
--
-- Cómo usar: en el dashboard de Supabase del proyecto nuevo → SQL Editor →
-- pegar TODO este archivo → antes de correrlo, CAMBIAR la contraseña de admin
-- en la línea marcada con  >>> CAMBIAR <<<  (al final de la sección 2) → Run.
--
-- Modelo de seguridad:
--   * RLS habilitado en todas las tablas y SIN policies para anon
--     → la clave pública (anon) NO puede leer ni escribir ninguna tabla directamente.
--   * Todo el acceso pasa por funciones RPC SECURITY DEFINER que validan
--     credenciales (bcrypt vía pgcrypto) en cada llamada.
--   * Las contraseñas se guardan hasheadas. No se pueden recuperar, solo resetear.
-- ============================================================

create extension if not exists pgcrypto;

-- ============================================================
-- 1. TABLAS
-- ============================================================

-- Proyectos de ley publicados a prospectos. Una fila por día de reporte.
-- Mismo formato de `data` que la tabla `projects` interna (array JSON de proyectos).
-- NUNCA contiene calificaciones de impacto ni nombres de clientes.
create table if not exists projects_public (
  id bigint generated by default as identity primary key,
  date date not null unique,
  data jsonb not null default '[]'::jsonb,
  synced_at timestamptz not null default now()
);

-- Cuentas de potenciales clientes.
create table if not exists prospect_accounts (
  id bigint generated by default as identity primary key,
  username text not null unique,
  pass_hash text not null,
  display_name text not null default '',      -- nombre de la empresa / contacto (se muestra en la app)
  sectors jsonb not null default '[]'::jsonb, -- lista de sectores permitidos; [] = todos
  jurs jsonb not null default '[]'::jsonb,    -- lista de jurisdicciones permitidas; [] = todas
  is_active boolean not null default true,
  expires_at date,                            -- null = sin vencimiento
  notes text not null default '',
  created_at timestamptz not null default now(),
  last_login timestamptz,
  login_count int not null default 0
);

-- Contraseña del módulo de administración (una sola fila).
create table if not exists admin_settings (
  id int primary key default 1,
  admin_hash text not null
);

-- RLS cerrado: sin policies → anon no toca nada directo.
alter table projects_public   enable row level security;
alter table prospect_accounts enable row level security;
alter table admin_settings    enable row level security;
revoke all on projects_public, prospect_accounts, admin_settings from anon, authenticated;

-- ============================================================
-- 2. CONTRASEÑA DE ADMIN
-- ============================================================

-- >>> CAMBIAR 'CAMBIAME_ADMIN' por la contraseña real del módulo admin <<<
insert into admin_settings (id, admin_hash)
values (1, crypt('CAMBIAME_ADMIN', gen_salt('bf')))
on conflict (id) do update set admin_hash = excluded.admin_hash;

-- (Para cambiarla más adelante, volver a correr solo este INSERT con la nueva clave.)

-- ============================================================
-- 3. HELPERS INTERNOS (no expuestos)
-- ============================================================

-- Valida la contraseña de admin. Lanza excepción si no coincide.
create or replace function _require_admin(p_admin text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not exists (
    select 1 from admin_settings
    where id = 1 and admin_hash = crypt(coalesce(p_admin,''), admin_hash)
  ) then
    raise exception 'admin_unauthorized';
  end if;
end $$;
revoke execute on function _require_admin(text) from public, anon, authenticated;

-- Valida credenciales de prospecto. Devuelve la cuenta o null.
create or replace function _prospect_auth(p_user text, p_pass text)
returns prospect_accounts language plpgsql security definer set search_path = public as $$
declare acc prospect_accounts;
begin
  select * into acc from prospect_accounts
  where lower(username) = lower(trim(coalesce(p_user,'')));
  if acc.id is null or acc.pass_hash <> crypt(coalesce(p_pass,''), acc.pass_hash) then
    return null;
  end if;
  return acc;
end $$;
revoke execute on function _prospect_auth(text, text) from public, anon, authenticated;

-- ============================================================
-- 4. RPC DE PROSPECTOS (usados por index.html)
-- ============================================================

-- Login: valida usuario+contraseña, estado y vencimiento. Registra el ingreso.
create or replace function prospect_login(p_user text, p_pass text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare acc prospect_accounts;
begin
  acc := _prospect_auth(p_user, p_pass);
  if acc.id is null then
    return jsonb_build_object('ok', false, 'reason', 'credenciales');
  end if;
  if not acc.is_active then
    return jsonb_build_object('ok', false, 'reason', 'inactiva');
  end if;
  if acc.expires_at is not null and acc.expires_at < current_date then
    return jsonb_build_object('ok', false, 'reason', 'vencida');
  end if;
  update prospect_accounts
    set last_login = now(), login_count = login_count + 1
    where id = acc.id;
  return jsonb_build_object(
    'ok', true,
    'display_name', acc.display_name,
    'sectors', acc.sectors,
    'jurs', acc.jurs,
    'expires_at', acc.expires_at
  );
end $$;

-- Proyectos visibles para la cuenta: últimos 30 días, filtrados por sector y
-- jurisdicción EN EL SERVIDOR (el prospecto nunca recibe lo que no le corresponde).
create or replace function prospect_projects(p_user text, p_pass text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare acc prospect_accounts;
begin
  acc := _prospect_auth(p_user, p_pass);
  if acc.id is null or not acc.is_active
     or (acc.expires_at is not null and acc.expires_at < current_date) then
    return jsonb_build_object('ok', false);
  end if;
  return jsonb_build_object('ok', true, 'days', coalesce((
    select jsonb_agg(jsonb_build_object('date', t.d, 'data', t.flt) order by t.d desc)
    from (
      select pp.date as d,
        (select coalesce(jsonb_agg(e), '[]'::jsonb)
           from jsonb_array_elements(pp.data) e
          where (acc.sectors = '[]'::jsonb or acc.sectors ? (e->>'sector'))
            and (acc.jurs    = '[]'::jsonb or acc.jurs    ? (e->>'jur'))
        ) as flt
      from projects_public pp
      where pp.date >= current_date - 30
    ) t
    where jsonb_array_length(t.flt) > 0
  ), '[]'::jsonb));
end $$;

-- ============================================================
-- 5. RPC DE ADMIN (usados por admin.html)
-- ============================================================

-- Gate del módulo admin.
create or replace function admin_check(p_admin text)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  perform _require_admin(p_admin);
  return true;
exception when others then
  return false;
end $$;

-- Vista general: cuentas (sin hashes) + días sincronizados con conteo.
create or replace function admin_overview(p_admin text)
returns jsonb language plpgsql security definer set search_path = public as $$
begin
  perform _require_admin(p_admin);
  return jsonb_build_object(
    'accounts', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', a.id, 'username', a.username, 'display_name', a.display_name,
        'sectors', a.sectors, 'jurs', a.jurs, 'is_active', a.is_active,
        'expires_at', a.expires_at, 'notes', a.notes, 'created_at', a.created_at,
        'last_login', a.last_login, 'login_count', a.login_count
      ) order by a.created_at desc)
      from prospect_accounts a
    ), '[]'::jsonb),
    'dates', coalesce((
      select jsonb_agg(jsonb_build_object(
        'date', pp.date, 'count', jsonb_array_length(pp.data), 'synced_at', pp.synced_at
      ) order by pp.date desc)
      from projects_public pp
    ), '[]'::jsonb)
  );
end $$;

-- Alta de cuenta. La contraseña se guarda hasheada (no recuperable).
create or replace function admin_create_account(
  p_admin text, p_username text, p_pass text, p_display text,
  p_sectors jsonb, p_jurs jsonb, p_expires date, p_notes text
) returns jsonb language plpgsql security definer set search_path = public as $$
declare new_id bigint;
begin
  perform _require_admin(p_admin);
  if length(trim(coalesce(p_username,''))) < 3 then
    return jsonb_build_object('ok', false, 'error', 'El usuario debe tener al menos 3 caracteres');
  end if;
  if length(coalesce(p_pass,'')) < 8 then
    return jsonb_build_object('ok', false, 'error', 'La contraseña debe tener al menos 8 caracteres');
  end if;
  if exists (select 1 from prospect_accounts where lower(username) = lower(trim(p_username))) then
    return jsonb_build_object('ok', false, 'error', 'Ese usuario ya existe');
  end if;
  insert into prospect_accounts (username, pass_hash, display_name, sectors, jurs, expires_at, notes)
  values (lower(trim(p_username)), crypt(p_pass, gen_salt('bf')), coalesce(p_display,''),
          coalesce(p_sectors,'[]'::jsonb), coalesce(p_jurs,'[]'::jsonb), p_expires, coalesce(p_notes,''))
  returning id into new_id;
  return jsonb_build_object('ok', true, 'id', new_id);
end $$;

-- Actualiza una cuenta (estado completo; p_expires null = sin vencimiento).
create or replace function admin_update_account(
  p_admin text, p_id bigint, p_display text,
  p_sectors jsonb, p_jurs jsonb, p_expires date, p_active boolean, p_notes text
) returns jsonb language plpgsql security definer set search_path = public as $$
begin
  perform _require_admin(p_admin);
  update prospect_accounts set
    display_name = coalesce(p_display, display_name),
    sectors = coalesce(p_sectors, sectors),
    jurs = coalesce(p_jurs, jurs),
    expires_at = p_expires,
    is_active = coalesce(p_active, is_active),
    notes = coalesce(p_notes, notes)
  where id = p_id;
  if not found then return jsonb_build_object('ok', false, 'error', 'Cuenta no encontrada'); end if;
  return jsonb_build_object('ok', true);
end $$;

-- Resetea la contraseña de una cuenta.
create or replace function admin_reset_password(p_admin text, p_id bigint, p_new_pass text)
returns jsonb language plpgsql security definer set search_path = public as $$
begin
  perform _require_admin(p_admin);
  if length(coalesce(p_new_pass,'')) < 8 then
    return jsonb_build_object('ok', false, 'error', 'La contraseña debe tener al menos 8 caracteres');
  end if;
  update prospect_accounts set pass_hash = crypt(p_new_pass, gen_salt('bf')) where id = p_id;
  if not found then return jsonb_build_object('ok', false, 'error', 'Cuenta no encontrada'); end if;
  return jsonb_build_object('ok', true);
end $$;

-- Elimina una cuenta.
create or replace function admin_delete_account(p_admin text, p_id bigint)
returns jsonb language plpgsql security definer set search_path = public as $$
begin
  perform _require_admin(p_admin);
  delete from prospect_accounts where id = p_id;
  return jsonb_build_object('ok', true);
end $$;

-- Sincroniza los proyectos de UN día (upsert por fecha) y limpia lo más viejo de 45 días.
create or replace function admin_sync_projects(p_admin text, p_date date, p_data jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
begin
  perform _require_admin(p_admin);
  insert into projects_public (date, data, synced_at)
  values (p_date, coalesce(p_data,'[]'::jsonb), now())
  on conflict (date) do update set data = excluded.data, synced_at = now();
  delete from projects_public where date < current_date - 45;
  return jsonb_build_object('ok', true, 'count', jsonb_array_length(coalesce(p_data,'[]'::jsonb)));
end $$;
